In [1]:
4 *7

28

In [2]:
3 + 7

10

In [55]:
5 - 2

3

In [56]:
5 ** 5

3125

In [57]:
x, y, z = 3,8,9

In [58]:
x

3

In [59]:
y

8

In [60]:
z

9

In [61]:
x*y + z

33

In [62]:
x =5

In [63]:
x

5

In [64]:
h=8

In [65]:
h

8

In [66]:
'data science nigeria'

'data science nigeria'

In [67]:
("DATA SCIENCE NIGERIA")

'DATA SCIENCE NIGERIA'

In [68]:
Num=34
name= "ADE"

In [69]:
print("my name is {} and my age is {}".format(name,Num))

my name is ADE and my age is 34


In [70]:
print("my name is {} and my age is {}".format(name,Num))

my name is ADE and my age is 34


In [71]:
d="good"

In [72]:
d[3]

'd'

In [73]:
T = "abcde"

In [74]:
T[3]

'd'

In [75]:
T [0:3]

'abc'

In [76]:
list =[4,5,6,7,8]

In [77]:
list

[4, 5, 6, 7, 8]

# list.append (1)

In [78]:
list

[4, 5, 6, 7, 8]

# Nested List

In [79]:
nest=[4,6,[1,5,8]]

In [80]:
nest[2][2]

8

# Dico

# you are driving a little too fast, and a police officer stops. write a function to return one of the results:
to return " no ticket", "small ticket"

In [81]:
def caught_speeding(speed, is_birthday):
    if is_birthday:
        speeding = speed - 5
    else:
        speeding = speed
    if speeding > 80:
        return 'Big Tickect'
    elif speeding > 60:
        return 'Small Ticket'
    else:
        return 'No Ticket'
caught_speeding(70, True)


'Small Ticket'

In [82]:
caught_speeding(50, True)

'No Ticket'

In [83]:
caught_speeding(90, True)

'Big Tickect'

# Numpy

In [84]:
import numpy as np

In [85]:
my_list=[1,2,3,4]

In [86]:
np.array(my_list)

array([1, 2, 3, 4])

In [87]:
arr=np.array(my_list)

In [88]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [90]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [91]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [92]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [93]:
np.asmatrix((3,4))

matrix([[3, 4]])

In [94]:
np.linspace(0,5)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [95]:
np.asmatrix((5.9))

matrix([[5.9]])

In [96]:
np.linspace(0,1000,10)

array([   0.        ,  111.11111111,  222.22222222,  333.33333333,
        444.44444444,  555.55555556,  666.66666667,  777.77777778,
        888.88888889, 1000.        ])

In [97]:
np.linspace(0,200,10)

array([  0.        ,  22.22222222,  44.44444444,  66.66666667,
        88.88888889, 111.11111111, 133.33333333, 155.55555556,
       177.77777778, 200.        ])

In [98]:
today=np.arange(0,10)

In [99]:
today

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
today[6]

6

In [101]:
today[1:5]

array([1, 2, 3, 4])

In [102]:
today[:]=10

In [103]:
today

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

### today[:4

# today

In [104]:
today[2:4]=6

In [105]:
today

array([10, 10,  6,  6, 10, 10, 10, 10, 10, 10])

In [106]:
tom=([1,3,2],[5,6,8],[6,9,8])


In [107]:
np.array(tom)

array([[1, 3, 2],
       [5, 6, 8],
       [6, 9, 8]])

In [108]:
import pandas as pd

In [109]:
import matplotlib as mp

In [110]:
import sklearn as sk

In [111]:
import seaborn as sb

In [8]:
import nltk

In [9]:
import math
import Numpy as np

ModuleNotFoundError: No module named 'Numpy'

In [ ]:
np.arrange(0,15,3)