# Numpy  

Numpy is a linear algebra library for python, the reason it is so important for Data science with Python is that almost 
all of the libraries in the PyData Ecosystem rely on Numpy as one of their main building blocks.

Numpy is also incredibly fast.

Installing into the computer. Anaconda Prompt
conda install numpy

## Numpy Arrays 

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3,4]

In [3]:
np.array(my_list)

array([1, 2, 3, 4])

In [4]:
arr = np.array(my_list)

In [5]:
np.arange(0,10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [7]:
np.zeros((5,5))  #First number represent the number of rows and the second represent the number of columns

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.linspace(0,5,10) #Equal 10 spaced number from 0 to 5

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [10]:
#Creating Identity matrix(Two dimensional square matrix)
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
#Random method, to generate arrays with random numbers
np.random.rand(5,5)

array([[0.82664025, 0.44467318, 0.66793832, 0.37040989, 0.66453939],
       [0.46306073, 0.64122896, 0.02384836, 0.72558322, 0.40699342],
       [0.67258866, 0.69005549, 0.05390462, 0.21367562, 0.42046148],
       [0.00584979, 0.46607459, 0.06358456, 0.84848607, 0.4840551 ],
       [0.48788773, 0.06560711, 0.7663707 , 0.52563307, 0.44877066]])

In [12]:
np.random.randn(4,5)

array([[ 1.18880245,  0.14763118, -1.3694016 ,  0.61960849,  0.48575705],
       [-0.03938205, -0.02015939,  0.39542133, -1.02816759,  0.0646947 ],
       [ 1.79287463,  0.4193593 ,  1.97656797,  0.93211979,  2.10278464],
       [ 1.8514356 ,  0.48505772,  0.12479995, -1.94586098, -0.21974863]])

In [13]:
rand = np.random.randint(0,90, 10)

In [14]:
rand

array([71, 22, 87, 89, 13, 26, 35, 40, 33, 81])

In [15]:
rand.max()

89

In [16]:
#Index Location of the max value
rand.argmax()

3

In [17]:
rand.dtype

dtype('int32')

## Numpy Indexing and Selection

In [18]:
arindx = np.arange(0,12)

In [19]:
arindx

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
arindx[9]

9

In [22]:
arindx[1:6]

array([1, 2, 3, 4, 5])

In [23]:
arindx[1:6] = 100

In [24]:
arindx

array([  0, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10,  11])

In [25]:
arindx = np.arange(0,11)

In [26]:
arindx

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
slice = arindx[1:6]

In [28]:
slice[:] = 10

In [29]:
#Broadcast
slice

array([10, 10, 10, 10, 10])

In [30]:
arindx

array([ 0, 10, 10, 10, 10, 10,  6,  7,  8,  9, 10])

In [31]:
#Copying Array
arr_copy = arindx.copy()

## Creating a 2D array

In [33]:
np_2d = np.array([[3,4,5], [5,6,7], [6,7,7]])

In [34]:
np_2d

array([[3, 4, 5],
       [5, 6, 7],
       [6, 7, 7]])

Grabbing numbers from the 2d array

Double Bracket format

np_2d = [row][column]

In [35]:
np_2d[2][2]

7

Single bracket format

In [36]:
np_2d[2,2]

7

In [37]:
#Using slice notation to grab multiple rows and columns
np_2d [:2,1:]

array([[4, 5],
       [6, 7]])

## Conditional Selection 

In [38]:
arry = np.arange(0,11)

In [42]:
bool_arry = arry > 5

In [43]:
#Conditionally select elemet where the boolean happens to be true
arry[bool_arry]

array([ 6,  7,  8,  9, 10])

In [44]:
#So we can express
arry[arry > 5]

array([ 6,  7,  8,  9, 10])

In [45]:
arry[arry<3]

array([0, 1, 2])